travis:
  secure:
    BINSTAR_TOKEN: R0IBbDX2blmOGsLYrJtIC2tELSROq9i0upi1UQtQcehObORtEOhAjp2puWQkMqkY//CwqhPWVcSkdHZFmTex0zec1R+YhaQNLykAEvSppUJgoyReeRLN4boKUPxZoFPn4De2lgxat7w5dlL+WP7x2xl8a+L1vcmESp3iY7guZlhEsSH0RRHzvGgSzGFCWVbKMeUtaceTQMmEzIxNXTKouf4hCKJKKH5urrSCS7Qac79Rq072fIxRgfIzs8Chb6kRcTF7QLqlAaZq0xV2dzcT76zb4vh6eVNlCuKLP0kO9Tq4vcdPEyP9lcZ6QjPuYD+YPDRc7ln++Ld0eUiC/bCnjW4AYQJ1kmBcyqTVmcEEw98jopU9O11Jbt2BafSHNXNzhOrR7n/7dCSD4Dnre84a577YdB8RxhPHBsCpUBmSR4JnM1e6jbHLUXLXpcjWyhnMJWghB2MpYTWbr7JXOl0bRv1pySy4O/x1dj9oTYai7Z6M9xIFPxdPPvMunWIPrrDRtehKoXn8e4nbl/kzvmsRNckctq+Yg1Q2iPgcZ5jZX83lfwDFevnhXI5Y/6I7uO2ut66g/9/umi3FYm5SpELxz9G2QrDKEC5k7AwcUVDcNFTiE1tWan6WUnuW26fHfUJEVQTtlkxKRo4T+nnNitoZ88G7hvXLjGVgiUaiR2a2CVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
